services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sensordata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sensordata"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data_pipeline_net

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestion
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - data_pipeline_net
    # Comando para ejecutar el script en un bucle cada hora
    command: sh -c "while true; do python run_publisher.py; echo 'Ingesta completada, esperando 1 hora para la próxima ejecución.'; sleep 3600; done"

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
      # Ya no dependemos de que 'ingestion' termine, sino de que 'postgres_db' esté lista
    networks:
      - data_pipeline_net

networks:
  data_pipeline_net:
    driver: bridge